### ISSUE TITLE
NavBar: Reformat Button/Header

### ISSUE THREAD

**Issue by JerJohn15** [JerJohn15/laverna#6]
The "<" icon should be a button, not a italic tag, <i>. The Header, "Close" should be changed to "NavBar", "Navigation Bar" or a better title. The current title, "Close" is obvious by the "X" button in the top right corner. The soon-to-be tooltip feature will make identifying what these icons do much easier, therefore making this title irrelevant. 

``` html

  <div class="list-group">
        <div class="list-group-item sidemenu--item -disabled sidemenu--close">
            <i class="icon-left-open-big"></i>//should be a button
            {{i18n('Close')}}
            <button type="button" class="close" aria-hidden="true">
                &times;
            </button>
        </div>
```

**ToDo**
- [x]  The  "<" and "X"  icons should only be clickable in the header **not** the header title as well `app/scripts/navbar/show/template.html`
- [x] Change the "Close" header tab to a better title.
- [x] Reformat the span tag that contains the header title so that the title appears properly.

Related Issue: #5.

**Comment by JerJohn15** [comment]
In order to achieve the first task, I will need to either create a new class or id with the hover effect removed or move the   ``sidemenu--close`class into the italics and button elements located in the **sidemenu.less** folder. 

Possible solution to removing hover effect in SideBar Header:

``` javascript

<div class="list-group">
        <div class="list-group-item sidemenu--item -disabled ">
            <i class="icon-left-open-big sidemenu--close"></i>
            {{i18n('Menu')}}
            <button type="button" class="close sidemenu--close" aria-hidden="true">
                &times;
            </button>
        </div>
```

**Comment by JerJohn15** [comment]
It was recommended in my pull request for the original copy of this project, to leave the menu header in both the sidebar and navigation bar clickable and instead have a key binding that opens and closes the menu. I will implement this instead and remove the unclickable functionality.
