### ISSUE TITLE
NavBar: Search Field should appear underneath "Search Icon"

### ISSUE THREAD

**Issue by JerJohn15** [JerJohn15/laverna#7]
Currently, the search button overlaps the NavBar header when the user clicks the "Q" image, so that the user does not see the header title and "icon-menu" image. This should be fixed. 

**Suggestion:** The search field should appear on the screen in way that does not blind the user to other areas of the application. Perhaps it could appear best towards the right of the "New Note" icon. Alternatively, it could also appear nicely underneath the "search", "new note" and "navbar menu" icons. 
If the latter option is chosen, perhaps one way to achieve this is to have the search bar appear underneath, while at the same time stretch the, currently white, background, thus bringing the "sidebar content" down a few inches. Since the search icon will be visible, the ability to close the search field should be enhanced to hiding when the "Q" icon is clicked, in addition to the condition that it will close if clicked anywhere outside the field itself (This might already be included under the condition, in which case, this step should be ignored). 
- [x] **Bug Fix:** The search bar should appear in a way that gives the user visibility of the application.
- [ ] **Suggestion 1:** The search bar could appear on the right side of the "New Note" icon 
- [x] **Suggestion 2:** The search bar could appear underneath the "New Note", "Menu NavBar", and "search icon". If this method is choosen, animation needs to be done so that the search field ~~expands and shrinks other parts of the application, specifically the navbar content, and navbar header background.~~

**Comment by JerJohn15** [comment]
One way to achieve this is to make the search bar appear as an accordion. This can be done through a combination of css, javascript, and html files (to create the effect, handle the process of the action event, and display the front end of the application).

**Steps to Create:**
1. Check for an action event on the search icon
2. Expand the search Icon. 

**Useful Resources:**
- [with pure css and html](https://www.youtube.com/watch?v=YE4xl9Gh7GE)
- [w3schools](http://www.w3schools.com/howto/howto_js_accordion.asp)
- [w3 wiki](https://www.w3.org/WAI/GL/wiki/Using_aria-expanded_to_indicate_the_state_of_a_collapsible_element)
- [codepen example](https://codepen.io/abergin/pen/ihlDf)

**Comment by JerJohn15** [comment]
I ended up using my second suggestion.
